CREATE DATABASE IF NOT EXISTS railway CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE railway;

CREATE TABLE IF NOT EXISTS roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    permissions JSON,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by INT,
    INDEX idx_name (name),
    INDEX idx_active (is_active)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    role_id INT,
    is_active BOOLEAN DEFAULT TRUE,
    last_login TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE SET NULL,
    INDEX idx_username (username),
    INDEX idx_email (email),
    INDEX idx_role (role_id),
    INDEX idx_active (is_active)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS departments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    manager_id INT,
    department_type ENUM('branding', 'planning', 'quality', 'maintenance', 'finance', 'warehouse', 'other') NOT NULL,
    daily_target DECIMAL(10,2),
    weekly_target DECIMAL(10,2),
    monthly_target DECIMAL(10,2),
    capacity_target DECIMAL(10,2),
    config JSON,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (manager_id) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_code (code),
    INDEX idx_type (department_type),
    INDEX idx_active (is_active)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS production_stages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    department_id INT NOT NULL,
    stage_name VARCHAR(200) NOT NULL,
    stage_order INT NOT NULL,
    description TEXT,
    estimated_duration_minutes INT,
    config JSON,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE,
    INDEX idx_department (department_id),
    INDEX idx_order (stage_order),
    INDEX idx_active (is_active)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS employees (
    id INT AUTO_INCREMENT PRIMARY KEY,
    employee_number VARCHAR(50) NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(50),
    department_id INT,
    position VARCHAR(100),
    employee_type ENUM('operator', 'supervisor', 'coordinator', 'manager', 'admin', 'applique_cutter', 'packer', 'technician', 'planner', 'qc') NOT NULL,
    user_id INT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_emp_number (employee_number),
    INDEX idx_department (department_id),
    INDEX idx_type (employee_type),
    INDEX idx_active (is_active)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS machines (
    id INT AUTO_INCREMENT PRIMARY KEY,
    machine_number VARCHAR(50) NOT NULL UNIQUE,
    machine_name VARCHAR(200) NOT NULL,
    department_id INT NOT NULL,
    machine_type VARCHAR(100),
    manufacturer VARCHAR(200),
    model VARCHAR(200),
    serial_number VARCHAR(200),
    purchase_date DATE,
    status ENUM('available', 'in_use', 'maintenance', 'broken', 'retired') DEFAULT 'available',
    config JSON,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE,
    INDEX idx_machine_number (machine_number),
    INDEX idx_department (department_id),
    INDEX idx_status (status),
    INDEX idx_active (is_active)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    product_code VARCHAR(100) NOT NULL UNIQUE,
    product_name VARCHAR(300) NOT NULL,
    description TEXT,
    category VARCHAR(100),
    specifications JSON,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_code (product_code),
    INDEX idx_category (category),
    INDEX idx_active (is_active)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_number VARCHAR(100) NOT NULL UNIQUE,
    sales_order_number VARCHAR(100),
    customer_name VARCHAR(300) NOT NULL,
    product_id INT,
    quantity INT NOT NULL,
    order_value DECIMAL(12,2),
    start_date DATE,
    end_date DATE,
    priority ENUM('low', 'normal', 'high', 'urgent') DEFAULT 'normal',
    status ENUM('unscheduled', 'scheduled', 'in_progress', 'completed', 'on_hold', 'cancelled') DEFAULT 'unscheduled',
    hold_reason TEXT,
    notes TEXT,
    config JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
    INDEX idx_order_number (order_number),
    INDEX idx_sales_order (sales_order_number),
    INDEX idx_customer (customer_name),
    INDEX idx_status (status),
    INDEX idx_dates (start_date, end_date)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS job_schedules (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    department_id INT NOT NULL,
    stage_id INT,
    scheduled_date DATE NOT NULL,
    scheduled_quantity INT NOT NULL,
    actual_quantity INT,
    machine_id INT,
    assigned_employee_id INT,
    status ENUM('scheduled', 'in_progress', 'completed', 'rejected', 'on_hold') DEFAULT 'scheduled',
    started_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE,
    FOREIGN KEY (stage_id) REFERENCES production_stages(id) ON DELETE SET NULL,
    FOREIGN KEY (machine_id) REFERENCES machines(id) ON DELETE SET NULL,
    FOREIGN KEY (assigned_employee_id) REFERENCES employees(id) ON DELETE SET NULL,
    INDEX idx_order (order_id),
    INDEX idx_department (department_id),
    INDEX idx_date (scheduled_date),
    INDEX idx_status (status),
    INDEX idx_machine (machine_id),
    INDEX idx_employee (assigned_employee_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS replacement_tickets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ticket_number VARCHAR(100) NOT NULL UNIQUE,
    order_id INT NOT NULL,
    product_id INT,
    quantity_rejected INT NOT NULL,
    department_id INT NOT NULL,
    stage_id INT,
    rejection_reason TEXT NOT NULL,
    rejection_type ENUM('material', 'workmanship', 'machine', 'design', 'other') NOT NULL,
    status ENUM('pending_approval', 'approved', 'replacement_processed', 'no_stock', 'rejected') DEFAULT 'pending_approval',
    created_by_id INT NOT NULL,
    approved_by_id INT,
    approved_at TIMESTAMP NULL,
    notes TEXT,
    config JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE,
    FOREIGN KEY (stage_id) REFERENCES production_stages(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (approved_by_id) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_ticket_number (ticket_number),
    INDEX idx_order (order_id),
    INDEX idx_department (department_id),
    INDEX idx_status (status),
    INDEX idx_created (created_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS customer_returns (
    id INT AUTO_INCREMENT PRIMARY KEY,
    return_number VARCHAR(100) NOT NULL UNIQUE,
    order_id INT NOT NULL,
    product_id INT,
    quantity_returned INT NOT NULL,
    return_reason TEXT NOT NULL,
    customer_complaint TEXT,
    return_date DATE NOT NULL,
    return_type ENUM('defect', 'wrong_item', 'damage', 'other') NOT NULL,
    recorded_by_id INT NOT NULL,
    notes TEXT,
    config JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
    FOREIGN KEY (recorded_by_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_return_number (return_number),
    INDEX idx_order (order_id),
    INDEX idx_return_date (return_date),
    INDEX idx_type (return_type)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sop_failure_tickets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ticket_number VARCHAR(100) NOT NULL UNIQUE,
    sop_reference VARCHAR(200) NOT NULL,
    failure_description TEXT NOT NULL,
    impact_description TEXT,
    charging_department_id INT NOT NULL,
    charged_department_id INT NOT NULL,
    original_charged_department_id INT NOT NULL,
    status ENUM('open', 'ncr_in_progress', 'ncr_completed', 'rejected', 'reassigned', 'escalated', 'closed') DEFAULT 'open',
    reassignment_reason TEXT,
    rejection_reason TEXT,
    escalated_to_hod BOOLEAN DEFAULT FALSE,
    hod_decision TEXT,
    hod_decided_by_id INT,
    hod_decision_date TIMESTAMP NULL,
    ncr_completed_at TIMESTAMP NULL,
    created_by_id INT NOT NULL,
    assigned_to_id INT,
    notes TEXT,
    config JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    closed_at TIMESTAMP NULL,
    FOREIGN KEY (charging_department_id) REFERENCES departments(id) ON DELETE CASCADE,
    FOREIGN KEY (charged_department_id) REFERENCES departments(id) ON DELETE CASCADE,
    FOREIGN KEY (original_charged_department_id) REFERENCES departments(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (assigned_to_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (hod_decided_by_id) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_ticket_number (ticket_number),
    INDEX idx_charged_dept (charged_department_id),
    INDEX idx_status (status),
    INDEX idx_escalated (escalated_to_hod),
    INDEX idx_created (created_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ncr_reports (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sop_ticket_id INT NOT NULL,
    root_cause_analysis TEXT NOT NULL,
    corrective_actions TEXT NOT NULL,
    preventive_measures TEXT NOT NULL,
    responsible_person_id INT,
    target_completion_date DATE,
    actual_completion_date DATE,
    effectiveness_verification TEXT,
    completed_by_id INT NOT NULL,
    approved_by_id INT,
    approved_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (sop_ticket_id) REFERENCES sop_failure_tickets(id) ON DELETE CASCADE,
    FOREIGN KEY (responsible_person_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (completed_by_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (approved_by_id) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_sop_ticket (sop_ticket_id),
    INDEX idx_completion (actual_completion_date)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS maintenance_tickets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ticket_number VARCHAR(100) NOT NULL UNIQUE,
    machine_id INT NOT NULL,
    department_id INT NOT NULL,
    issue_description TEXT NOT NULL,
    severity ENUM('low', 'medium', 'high', 'critical') DEFAULT 'medium',
    status ENUM('open', 'assigned', 'in_progress', 'awaiting_parts', 'completed', 'cancelled') DEFAULT 'open',
    reported_by_id INT NOT NULL,
    assigned_to_id INT,
    priority_order INT,
    expected_start_time TIMESTAMP NULL,
    expected_completion_time TIMESTAMP NULL,
    actual_start_time TIMESTAMP NULL,
    actual_completion_time TIMESTAMP NULL,
    work_performed TEXT,
    parts_used TEXT,
    downtime_minutes INT,
    notes TEXT,
    config JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (machine_id) REFERENCES machines(id) ON DELETE CASCADE,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE,
    FOREIGN KEY (reported_by_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (assigned_to_id) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_ticket_number (ticket_number),
    INDEX idx_machine (machine_id),
    INDEX idx_department (department_id),
    INDEX idx_status (status),
    INDEX idx_severity (severity),
    INDEX idx_assigned (assigned_to_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS bom (
    id INT AUTO_INCREMENT PRIMARY KEY,
    product_id INT NOT NULL,
    version VARCHAR(50) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    effective_date DATE NOT NULL,
    notes TEXT,
    created_by_id INT NOT NULL,
    approved_by_id INT,
    approved_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (approved_by_id) REFERENCES users(id) ON DELETE SET NULL,
    UNIQUE KEY unique_product_version (product_id, version),
    INDEX idx_product (product_id),
    INDEX idx_active (is_active),
    INDEX idx_effective_date (effective_date)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS bom_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    bom_id INT NOT NULL,
    item_code VARCHAR(100) NOT NULL,
    item_description VARCHAR(300) NOT NULL,
    quantity_per_unit DECIMAL(10,4) NOT NULL,
    unit_of_measure VARCHAR(50) NOT NULL,
    unit_cost DECIMAL(12,4) NOT NULL,
    total_cost DECIMAL(12,4) GENERATED ALWAYS AS (quantity_per_unit * unit_cost) STORED,
    material_type VARCHAR(100),
    supplier VARCHAR(200),
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (bom_id) REFERENCES bom(id) ON DELETE CASCADE,
    INDEX idx_bom (bom_id),
    INDEX idx_item_code (item_code)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS dynamic_forms (
    id INT AUTO_INCREMENT PRIMARY KEY,
    form_name VARCHAR(200) NOT NULL UNIQUE,
    form_code VARCHAR(100) NOT NULL UNIQUE,
    module VARCHAR(100) NOT NULL,
    description TEXT,
    form_definition JSON NOT NULL,
    validation_rules JSON,
    workflow_config JSON,
    sla_config JSON,
    is_active BOOLEAN DEFAULT TRUE,
    version INT DEFAULT 1,
    created_by_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_form_code (form_code),
    INDEX idx_module (module),
    INDEX idx_active (is_active)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS form_submissions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    form_id INT NOT NULL,
    reference_number VARCHAR(100) NOT NULL UNIQUE,
    submission_data JSON NOT NULL,
    status VARCHAR(100) DEFAULT 'submitted',
    submitted_by_id INT NOT NULL,
    department_id INT,
    workflow_state JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (form_id) REFERENCES dynamic_forms(id) ON DELETE CASCADE,
    FOREIGN KEY (submitted_by_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL,
    INDEX idx_form (form_id),
    INDEX idx_reference (reference_number),
    INDEX idx_status (status),
    INDEX idx_submitted_by (submitted_by_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS notifications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    recipient_id INT NOT NULL,
    notification_type VARCHAR(100) NOT NULL,
    title VARCHAR(300) NOT NULL,
    message TEXT NOT NULL,
    related_entity_type VARCHAR(100),
    related_entity_id INT,
    is_read BOOLEAN DEFAULT FALSE,
    read_at TIMESTAMP NULL,
    action_url VARCHAR(500),
    priority ENUM('low', 'normal', 'high', 'urgent') DEFAULT 'normal',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (recipient_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_recipient (recipient_id),
    INDEX idx_type (notification_type),
    INDEX idx_read (is_read),
    INDEX idx_created (created_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS email_reports (
    id INT AUTO_INCREMENT PRIMARY KEY,
    report_name VARCHAR(200) NOT NULL,
    report_type VARCHAR(100) NOT NULL,
    report_config JSON NOT NULL,
    schedule_config JSON NOT NULL,
    recipients JSON NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    last_run_at TIMESTAMP NULL,
    next_run_at TIMESTAMP NULL,
    created_by_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_report_type (report_type),
    INDEX idx_active (is_active),
    INDEX idx_next_run (next_run_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS audit_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id INT,
    old_values JSON,
    new_values JSON,
    ip_address VARCHAR(50),
    user_agent TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_user (user_id),
    INDEX idx_action (action),
    INDEX idx_entity (entity_type, entity_id),
    INDEX idx_created (created_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS system_settings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    setting_key VARCHAR(100) NOT NULL UNIQUE,
    setting_value JSON NOT NULL,
    description TEXT,
    category VARCHAR(100),
    is_public BOOLEAN DEFAULT FALSE,
    updated_by_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (updated_by_id) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_key (setting_key),
    INDEX idx_category (category)
) ENGINE=InnoDB;

INSERT INTO roles (name, description, permissions) VALUES
('System Admin', 'Full system access with all permissions', '{"all": true}'),
('Department Manager', 'Manage department operations and employees', '{"department": {"read": true, "write": true, "manage_employees": true}}'),
('Planner', 'Schedule and plan production orders', '{"planning": {"read": true, "write": true, "schedule": true}}'),
('Operator', 'Execute production jobs', '{"jobs": {"read": true, "execute": true}}'),
('QC Coordinator', 'Manage quality control and defects', '{"qc": {"read": true, "write": true, "approve": true}}'),
('Maintenance Technician', 'Handle machinery maintenance', '{"maintenance": {"read": true, "write": true}}');

CREATE TABLE IF NOT EXISTS workflows (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workflow_name VARCHAR(200) NOT NULL UNIQUE,
    workflow_code VARCHAR(100) NOT NULL UNIQUE,
    module VARCHAR(100) NOT NULL,
    description TEXT,
    workflow_steps JSON NOT NULL,
    approval_rules JSON,
    escalation_rules JSON,
    is_active BOOLEAN DEFAULT TRUE,
    version INT DEFAULT 1,
    created_by_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_workflow_code (workflow_code),
    INDEX idx_module (module),
    INDEX idx_active (is_active)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sla_configurations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sla_name VARCHAR(200) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    department_id INT,
    priority ENUM('low', 'normal', 'high', 'critical') DEFAULT 'normal',
    response_time_minutes INT,
    resolution_time_minutes INT,
    escalation_levels JSON NOT NULL,
    notification_rules JSON,
    is_active BOOLEAN DEFAULT TRUE,
    created_by_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_entity_type (entity_type),
    INDEX idx_department (department_id),
    INDEX idx_priority (priority),
    INDEX idx_active (is_active)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sla_tracking (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sla_config_id INT NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id INT NOT NULL,
    status ENUM('on_track', 'at_risk', 'breached', 'resolved') DEFAULT 'on_track',
    response_due_at TIMESTAMP NULL,
    resolution_due_at TIMESTAMP NULL,
    responded_at TIMESTAMP NULL,
    resolved_at TIMESTAMP NULL,
    current_escalation_level INT DEFAULT 0,
    escalation_history JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (sla_config_id) REFERENCES sla_configurations(id) ON DELETE CASCADE,
    INDEX idx_entity (entity_type, entity_id),
    INDEX idx_status (status),
    INDEX idx_response_due (response_due_at),
    INDEX idx_resolution_due (resolution_due_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS field_permissions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    role_id INT NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    field_name VARCHAR(100) NOT NULL,
    permission_type ENUM('hidden', 'read_only', 'editable') DEFAULT 'editable',
    conditional_rules JSON,
    created_by_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE KEY unique_role_field (role_id, entity_type, field_name),
    INDEX idx_role (role_id),
    INDEX idx_entity (entity_type)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS preventive_maintenance_schedules (
    id INT AUTO_INCREMENT PRIMARY KEY,
    schedule_name VARCHAR(200) NOT NULL,
    machine_id INT NOT NULL,
    maintenance_type VARCHAR(100) NOT NULL,
    description TEXT,
    frequency_type ENUM('daily', 'weekly', 'monthly', 'quarterly', 'yearly', 'hours_based', 'cycles_based') NOT NULL,
    frequency_value INT NOT NULL,
    last_performed_at TIMESTAMP NULL,
    next_due_at TIMESTAMP NULL,
    estimated_duration_minutes INT,
    assigned_technician_id INT,
    priority ENUM('low', 'medium', 'high', 'critical') DEFAULT 'medium',
    checklist JSON,
    parts_required JSON,
    is_active BOOLEAN DEFAULT TRUE,
    created_by_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (machine_id) REFERENCES machines(id) ON DELETE CASCADE,
    FOREIGN KEY (assigned_technician_id) REFERENCES employees(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_machine (machine_id),
    INDEX idx_next_due (next_due_at),
    INDEX idx_active (is_active)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS preventive_maintenance_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    schedule_id INT NOT NULL,
    performed_at TIMESTAMP NOT NULL,
    performed_by_id INT NOT NULL,
    duration_minutes INT,
    checklist_results JSON,
    parts_used JSON,
    observations TEXT,
    next_recommended_date DATE,
    status ENUM('completed', 'partially_completed', 'skipped', 'rescheduled') DEFAULT 'completed',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (schedule_id) REFERENCES preventive_maintenance_schedules(id) ON DELETE CASCADE,
    FOREIGN KEY (performed_by_id) REFERENCES employees(id) ON DELETE CASCADE,
    INDEX idx_schedule (schedule_id),
    INDEX idx_performed_at (performed_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS labor_cost_models (
    id INT AUTO_INCREMENT PRIMARY KEY,
    department_id INT NOT NULL,
    position VARCHAR(100) NOT NULL,
    hourly_rate DECIMAL(10,2) NOT NULL,
    overtime_rate DECIMAL(10,2),
    benefits_percentage DECIMAL(5,2),
    effective_from DATE NOT NULL,
    effective_to DATE,
    is_active BOOLEAN DEFAULT TRUE,
    created_by_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_department (department_id),
    INDEX idx_position (position),
    INDEX idx_effective_dates (effective_from, effective_to),
    INDEX idx_active (is_active)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS overhead_cost_models (
    id INT AUTO_INCREMENT PRIMARY KEY,
    department_id INT NOT NULL,
    cost_category VARCHAR(100) NOT NULL,
    cost_description TEXT,
    cost_type ENUM('fixed', 'variable', 'semi_variable') NOT NULL,
    allocation_method ENUM('per_unit', 'per_hour', 'percentage', 'fixed_monthly') NOT NULL,
    cost_amount DECIMAL(12,2) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    is_active BOOLEAN DEFAULT TRUE,
    created_by_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_department (department_id),
    INDEX idx_category (cost_category),
    INDEX idx_effective_dates (effective_from, effective_to),
    INDEX idx_active (is_active)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS production_cost_tracking (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    job_schedule_id INT,
    material_cost DECIMAL(12,2) DEFAULT 0,
    labor_cost DECIMAL(12,2) DEFAULT 0,
    overhead_cost DECIMAL(12,2) DEFAULT 0,
    total_cost DECIMAL(12,2) GENERATED ALWAYS AS (material_cost + labor_cost + overhead_cost) STORED,
    cost_details JSON,
    calculated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    calculated_by_id INT,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (job_schedule_id) REFERENCES job_schedules(id) ON DELETE SET NULL,
    FOREIGN KEY (calculated_by_id) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_order (order_id),
    INDEX idx_job_schedule (job_schedule_id),
    INDEX idx_calculated_at (calculated_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS d365_integration_config (
    id INT AUTO_INCREMENT PRIMARY KEY,
    config_name VARCHAR(200) NOT NULL UNIQUE,
    endpoint_url VARCHAR(500) NOT NULL,
    auth_type ENUM('oauth', 'api_key', 'basic') NOT NULL,
    auth_credentials JSON NOT NULL,
    sync_entities JSON NOT NULL,
    sync_frequency_minutes INT DEFAULT 60,
    field_mappings JSON NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    last_sync_at TIMESTAMP NULL,
    next_sync_at TIMESTAMP NULL,
    created_by_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_active (is_active),
    INDEX idx_next_sync (next_sync_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS d365_sync_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    config_id INT NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    sync_direction ENUM('import', 'export', 'bidirectional') NOT NULL,
    records_processed INT DEFAULT 0,
    records_success INT DEFAULT 0,
    records_failed INT DEFAULT 0,
    status ENUM('in_progress', 'completed', 'failed', 'partial') DEFAULT 'in_progress',
    error_details JSON,
    sync_started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sync_completed_at TIMESTAMP NULL,
    FOREIGN KEY (config_id) REFERENCES d365_integration_config(id) ON DELETE CASCADE,
    INDEX idx_config (config_id),
    INDEX idx_entity_type (entity_type),
    INDEX idx_status (status),
    INDEX idx_sync_started (sync_started_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS employee_machine_allocations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    employee_id INT NOT NULL,
    machine_id INT NOT NULL,
    allocation_type ENUM('primary', 'secondary', 'backup') DEFAULT 'primary',
    start_date DATE NOT NULL,
    end_date DATE,
    is_active BOOLEAN DEFAULT TRUE,
    allocated_by_id INT NOT NULL,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
    FOREIGN KEY (machine_id) REFERENCES machines(id) ON DELETE CASCADE,
    FOREIGN KEY (allocated_by_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_employee (employee_id),
    INDEX idx_machine (machine_id),
    INDEX idx_active (is_active),
    INDEX idx_dates (start_date, end_date)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS order_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    item_sequence INT NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(12,2),
    total_price DECIMAL(12,2) GENERATED ALWAYS AS (quantity * unit_price) STORED,
    status ENUM('pending', 'in_progress', 'completed', 'rejected', 'on_hold') DEFAULT 'pending',
    specifications JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    INDEX idx_order (order_id),
    INDEX idx_product (product_id),
    INDEX idx_status (status)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS workflow_instance_tracking (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workflow_id INT NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id INT NOT NULL,
    current_step INT DEFAULT 0,
    workflow_state JSON NOT NULL,
    status ENUM('pending', 'in_progress', 'completed', 'rejected', 'cancelled') DEFAULT 'pending',
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL,
    assigned_to_id INT,
    FOREIGN KEY (workflow_id) REFERENCES workflows(id) ON DELETE CASCADE,
    FOREIGN KEY (assigned_to_id) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_workflow (workflow_id),
    INDEX idx_entity (entity_type, entity_id),
    INDEX idx_status (status),
    INDEX idx_assigned (assigned_to_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS order_production_paths (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    path_sequence INT NOT NULL,
    department_id INT NOT NULL,
    stage_id INT,
    estimated_duration_minutes INT,
    is_required BOOLEAN DEFAULT TRUE,
    notes TEXT,
    created_by_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE,
    FOREIGN KEY (stage_id) REFERENCES production_stages(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE KEY unique_order_sequence (order_id, path_sequence),
    INDEX idx_order (order_id),
    INDEX idx_department (department_id),
    INDEX idx_sequence (path_sequence)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS whatsapp_sessions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    phone_number VARCHAR(50) NOT NULL,
    employee_id INT,
    session_state ENUM('idle', 'awaiting_menu', 'awaiting_input') DEFAULT 'idle',
    current_flow VARCHAR(100),
    context_data JSON,
    last_message_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE SET NULL,
    INDEX idx_phone (phone_number),
    INDEX idx_employee (employee_id),
    INDEX idx_state (session_state),
    INDEX idx_expires (expires_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS whatsapp_messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_id INT,
    phone_number VARCHAR(50) NOT NULL,
    message_id VARCHAR(255),
    direction ENUM('inbound', 'outbound') NOT NULL,
    message_type ENUM('text', 'interactive', 'button', 'list', 'image', 'document') DEFAULT 'text',
    message_content TEXT NOT NULL,
    payload JSON,
    status ENUM('sent', 'delivered', 'read', 'failed') DEFAULT 'sent',
    error_message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES whatsapp_sessions(id) ON DELETE SET NULL,
    INDEX idx_session (session_id),
    INDEX idx_phone (phone_number),
    INDEX idx_direction (direction),
    INDEX idx_created (created_at),
    INDEX idx_message_id (message_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS whatsapp_interactions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_id INT NOT NULL,
    employee_id INT,
    interaction_type ENUM('reject', 'return', 'sop_failure', 'track', 'pull_data') NOT NULL,
    action_taken VARCHAR(255),
    reference_id INT,
    reference_type VARCHAR(100),
    request_data JSON,
    response_data JSON,
    status ENUM('initiated', 'completed', 'failed', 'cancelled') DEFAULT 'initiated',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL,
    FOREIGN KEY (session_id) REFERENCES whatsapp_sessions(id) ON DELETE CASCADE,
    FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE SET NULL,
    INDEX idx_session (session_id),
    INDEX idx_employee (employee_id),
    INDEX idx_type (interaction_type),
    INDEX idx_status (status),
    INDEX idx_reference (reference_type, reference_id)
) ENGINE=InnoDB;

INSERT INTO roles (name, description, permissions) VALUES
('System Admin', 'Full system access with all permissions', '{"all": true}'),
('Department Manager', 'Manage department operations and employees', '{"department": {"read": true, "write": true, "manage_employees": true}}'),
('Planner', 'Schedule and plan production orders', '{"planning": {"read": true, "write": true, "schedule": true}}'),
('Operator', 'Execute production jobs', '{"jobs": {"read": true, "execute": true}}'),
('QC Coordinator', 'Manage quality control and defects', '{"qc": {"read": true, "write": true, "approve": true}}'),
('Maintenance Technician', 'Handle machinery maintenance', '{"maintenance": {"read": true, "write": true}}');

INSERT INTO users (username, password_hash, email, first_name, last_name, role_id) VALUES
('admin@barron', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYzpLaEg7dO', 'admin@barron.com', 'System', 'Administrator', 1);
